aklomp/base64

lib/codec_avx2.c, lib/codec_ssse3.c
The `enc_translate` function now uses less instructions and only 3 constants.
Speed-up on `Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz` using `Apple LLVM version 8.0.0 (clang-800.0.38)`
AVX2: +45% compared to previous version
SSSE3: +54% compared to previous version
The AVX2 flavor uses:
- 3 add/sub instructions
- 1 comparison instruction
- 1 shuffle instruction
The SSSE3 flavor uses:
- 3 add/sub instructions
- 1 comparison instruction
- 1 shuffle instruction
- 3 copy instructions
Full results before & after modifications follows.
Before:
```
Filling buffer with 10.0 MB of random data...
Testing with buffer size 10 MB, fastest of 10 * 1
AVX2	encode	5772.70 MB/sec
AVX2	decode	6373.58 MB/sec
plain	encode	1344.26 MB/sec
plain	decode	1446.26 MB/sec
SSSE3	encode	3562.93 MB/sec
SSSE3	decode …
```
=> Improve SSSE3 and AVX2 encoding speed

lib/codec_avx2.c, lib/codec_ssse3.c
The dec_reshuffle function now uses less instructions.
Speed-up on `Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz` using `Apple LLVM version 8.0.0 (clang-800.0.38)`
AVX2: +8.5% compared to previous version
SSSE3: +8% compared to previous version
Speed-up is much less than #16 but there's one significant enough I think.
Full results before & after modifications follows.
Before:
```
Filling buffer with 10.0 MB of random data...
Testing with buffer size 10 MB, fastest of 100 * 1
AVX2	encode	7829.44 MB/sec
AVX2	decode	6388.09 MB/sec
plain	encode	1499.43 MB/sec
plain	decode	1556.07 MB/sec
SSSE3	encode	5600.94 MB/sec
SSSE3	decode	3577.29 MB/sec
Testing with buffer size 1 MB, fastest of 100 * 10
AVX2	encode	8968.92 MB/sec
AVX2	decode	6495.38 MB/sec
plain	encode	1500.98 MB/sec
plain	decode	1562.21 …
```
=> Improve SSSE3 and AVX2 decoding speed

lib/codecs.h, lib/dec/head.c, lib/dec/tail.c, test/test_base64.c
Decoder can succeed with invalid input.
This fixes this issue and add tests for this case.
=> Fix invalid input handling

Makefile, test/Makefile, test/benchmark.c
Modified Makefile to use -r instead of --relocatable so that it can be
used with MacOS linker as well.
Modified test/Makefile not to link with librt under MacOS.
Modified test/benchmark.c to use MACH time functions under MacOS.
=> Add build support for MacOS

lib/codec_avx2.c
Modified AVX2 `enc_reshuffle` function to use a blend instruction instead of 3 logical (2 * and, 1 * or) instructions. Also removes the need for 2 constants.
Speed-up on `Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz` using `Apple LLVM version 8.0.0 (clang-800.0.38)`
AVX2: +8% compared to previous version
Full results before & after modifications follows.
Before:
```
Filling buffer with 10.0 MB of random data...
Testing with buffer size 10 MB, fastest of 100 * 1
AVX2    encode  7876.40 MB/sec
AVX2    decode  7047.91 MB/sec
plain   encode  1499.65 MB/sec
plain   decode  1557.21 MB/sec
SSSE3   encode  5612.09 MB/sec
SSSE3   decode  3883.52 MB/sec
Testing with buffer size 1 MB, fastest of 100 * 10
AVX2    encode  8970.38 MB/sec
AVX2    decode  7093.07 MB/sec
plain   encode  1501.03 MB/sec
plain …
```
=> Improve AVX2 encoding speed

lib/arch/neon32/dec_loop.c
The decoding loop now uses a single `vbslq_u8` (select instruction)
instead of one `vorrq_u8` and one `vandq_u8` instructions for each
delta update.
Speed-up on `iPhone SE` using `Apple LLVM version 8.0.0 (clang-800.0.38)`
NEON32: +7% compared to previous version
Full results before & after modifications follows. I also added timings with innermost loop unrolled (+40%). Seems unrolling was reverted to standard looping after some benchmark with `Raspberry Pi 2B` and `Clang`. The combination I'm using definitely prefers the unrolled version (was also the case with previous version which falls in between `After` and `After unrolled`). 
Before:
```
Filling buffer with 10.0 MB of random data...
Testing with buffer size 10 MB, fastest of 100 * 1
NEON32	encode	2940.06 MB/sec
NEON32	decode …
```
=> Improve NEON32 decoding speed

lib/codec_choose.c
XSAVE_XRSTORE/AVX2/AVX bits were checked after a `CPUID.(EAX=07H,
ECX=0H)` call.
Only AVX2 flag shall be checked after that call.
Check for XSAVE_XRSTORE/AVX shall be done after a `CPUID.(EAX=01H,
ECX=0H)` call.
Update #29
=> Fix AVX/AVX2 runtime detection

test/codec_supported.h
When building from Xcode, the link stage fails with an error on
duplicated symbols.
```
duplicate symbol _codecs in:
/Users/Matt/Library/Developer/Xcode/DerivedData/base64-agluyaxujspnxhfchqvuyxeextlu/Build/Intermediates/base64.build/Debug/test_base64.build/Objects-normal/x86_64/test_base64.o
/Users/Matt/Library/Developer/Xcode/DerivedData/base64-agluyaxujspnxhfchqvuyxeextlu/Build/Intermediates/base64.build/Debug/test_base64.build/Objects-normal/x86_64/codec_supported.o
```
Adding extern to the symbol declaration in the header file fixes this
issue.
=> Fix build under Xcode

LICENSE, README.md, lib/arch/avx/codec.c, lib/arch/avx2/codec.c, lib/arch/avx2/enc_loop.c, lib/arch/sse41/codec.c, lib/arch/sse42/codec.c, lib/arch/ssse3/_mm_bswap_epi32.c, lib/arch/ssse3/codec.c, lib/arch/ssse3/enc_reshuffle.c
Use Wojciech Mula (@WojciechMula) implementation update for AVX2 /
SSSE3 encoding.
SSSE3 implementation is reused in SSE4.1, SSE4.2 and AVX dispatched
encoding loops.
SSE4.1 implementation is now useless but kept to ease integration of
future updates if needed.
Speed-up on i7-4870HQ @ 2.5 GHz (clang-800.0.42.1, x86_64)
SSSE3 encoding: +20%
SSE4.2 encoding: +8%
AVX encoding: +7%
AVX2 encoding: +3%
=> SSSE3->AVX2 encoding optimization

lib/arch/avx/codec.c, lib/arch/avx2/codec.c, lib/arch/neon32/codec.c, lib/arch/neon64/codec.c, lib/arch/sse41/codec.c, lib/arch/sse42/codec.c, lib/arch/ssse3/codec.c
MSVC compiler does not define those `__SIMD__` (e.g. `__AVX__`) predefined macros. 
Conditional code is now only dependent on config.h values in all `codec.c` files except for NEON which also includes the same checks as in `codec_choose.c`.
This fixes mayeut/pybase64#8 and probably aklomp/base64#40
=> Do the same checks in codecs than in codec_choose

CMakeLists.txt, README.md, bin/CMakeLists.txt, test/CMakeLists.txt
Hi,
Here are some fixes after the recent pull of cmake support.
- when enabling OpenMP also link against openmp lib, otherwise still not enabled
- not only build test tools but also install them (this is needed for Yocto recipe to pick them up and package)
- also build base64 command line encoder
- shutup warnings on recent versions of cmake (optional, @burn care to review this?)
- updated edison x86_64 benchmarks (optional)
My motherboard i7-4770 @ 3.4 GHz DDR1600 died, I won't be able to update these. I could provide a set on i7-10700 CPU @ 2.90GHz DDR4 3200?
=> Some fixes to cmake files

CMakeLists.txt
`DLL`s (not `SO`s) are RUNTIME targets which were previously installed
into the `lib/` directory instead of `bin/`.
=> [cmake] Install all RUNTIME targets into `bin/`

CMakeLists.txt, cmake/Modules/TargetArch.cmake
Set boolean variables based on the `OUTPUT_VARIABLE` and the detected
architecture name and use them for architecture dependent option
availability testing.
Earlier CMake versions (< 3.22) evaluate the `<depends>` parameter of
`cmake_dependent_option()` in a way which prevents `STREQUAL` based
conditions to be meaningfully evaluated. See [CMP0127] for details.
Fixes #93 
[CMP0127]: https://cmake.org/cmake/help/v3.23/policy/CMP0127.html
=> [cmake] Fix architecture dependent option selection

lib/arch/neon64/enc_loop_asm.c
Specifically "R" is a valid string literal prefix which causes compiler errors on gcc.
Fixes: https://github.com/aklomp/base64/issues/99
=> NEON64: enc: avoid reserved tokens in macro arguments

.github/workflows/test.yml, CMakeLists.txt, lib/arch/avx/codec.c, lib/arch/avx2/codec.c
Inline assembly builds are failing in 32-bit, only enable AVX/AVX2 inline assembly in 64-bit mode.
This was already done for SSE* codecs.
Add tests for 32-bit builds.
=> Fix i686 builds

.github/workflows/test.yml, test/Makefile, test/ci/analysis.sh, test/test_base64.c
This PR updates the workflow to run some static / dynamic analysis before running all other jobs.
It updates the unit test in order to get a reproducer for #111
=> chore(ci): run static/dynamic analysis

lib/codec_choose.c
The old/faulty code would try to use AVX/AVX2 if either the SSE bit or the AVX bit were set in XCR0, but did not check if both bits were set.
In most cases, this still worked, but on some machines, enabling linux kernel mitigations for the "gather data sampling" vulnerability results in only the SSE bit but not the AVX bit being set, thus resulting in an illegal instruction and crashing the application.
Fix this by checking that both bits are set.
Fixes: 4bbb590bd047e7d877bf9cc9218ee525ceca1a9b ("Proper check of CPU's AVX2 feature support (with MSVC support)")
=> Fix AVX detection

.github/workflows/test.yml, CMakeLists.txt, bin/base64.manifest, bin/base64.rc, test/ci/.gitattributes, test/ci/checksums.txt, test/ci/😵‍💫.bin
This notably allows passing unicode filenames as commandline arguments to the demo utility `bin/base64` without them being mangled in case the unicode filename cannot be represented in the currently active system code page.
Note that this only works/takes effect on Windows 10 Version 1903 and later. This is only integrated with CMake as I don't know how to portably invoke the resource compiler in a Makefile. I also added a test case for the CI.
See-Also: https://learn.microsoft.com/en-us/windows/apps/design/globalizing/use-utf8-code-page
Resolves #138
=> fix: Set active CP to UTF-8 on Windows 10 and 11

.github/workflows/test.yml
With macOS-11 runner removal, the test workflow is failing: use macOS-12 and enable AVX2 testing on macOS.
Update `actions/checkout` to `v4` to remove the node.js deprecation warning.
Add macOS-14 arm64 tests.
=> chore(ci): update deprecated actions & runners, add macos arm64 tests

.github/workflows/test.yml, lib/codec_choose.c, test/benchmark.c, test/ci/analysis.sh, test/ci/test.sh, test/codec_supported.c, test/codec_supported.h, test/test_base64.c
The typo results in a build error when AVX512 is enabled.
This should have been caught by CI but CI disables things that can't be tested: rework CI & tests to build everything and skip tests that can't be run.
We could probably add a test using Intel SDE in order to test everything but that would be for another PR.
based on #144 which fixes the CI workflow.
fixes #146
fixes #147
=> fix: typo in macro _AVX_512_ENABLED_BY_OS

.github/workflows/test.yml
Fixes workflow and add some tests on Linux aarch64
=> chore(ci): update deprecated runners, add linux aarch64 tests
